[
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Ancient Rome During Domitian’s Reign\n\n## General Layout\nRome sat on seven hills along the east bank of the Tiber River, about 25 km from the sea (Ostia).\nBy Domitian’s time, it had over a million inhabitants, making it the largest city in the ancient world.\nThe Forum Romanum (Roman Forum) was the political and ceremonial heart, surrounded by temples, basilicas, and government buildings.\nStreets were narrow and crowded, filled with multi-story insulae (apartment blocks), taverns, and markets.\n\n---\n\n## Urban Feel\nThe skyline was dominated by marble temples and domes.\nStreets were alive with carts, vendors, slaves, and patricians carried in litters.\nPublic fountains and aqueduct-fed waterworks supplied the population.\nAt night, the city was dimly lit and often dangerous — fire and crime were constant threats.\n\n---\n\n## The Major Hills and Districts\n### Palatine Hill\nThe imperial residence stood here — the Palatium, from which we get the word palace.\nDomitian rebuilt and expanded the imperial palace complex into the Domus Flavia (for state business) and Domus Augustana (his private quarters).\nThe palace overlooked both the Forum and the Circus Maximus.\nThe Palatine was heavily fortified, symbolizing imperial power.\n\n### Capitoline Hill — Temple, Jupiter, Archives, Government  \nNext to the Forum, it held the Temple of Jupiter Optimus Maximus, Rome’s most sacred shrine.\nAlso home to government buildings and archives.\n\n### Aventine Hill — Residential, Temples, Nobility  \nA more residential and quieter district, housing wealthy families and temples (like that of Diana).\n\n### Esquiline, Quirinal, Viminal Hills — Housing, Gardens, Population  \nDensely populated areas, filled with insulae (apartment blocks) and gardens.\nThe Esquiline also held parts of Nero’s former Domus Aurea (“Golden House”), which Vespasian and Titus replaced with public structures.\n\n---\n\n## The Colosseum (Flavian Amphitheater)\nLocated just east of the Forum, in the valley between the Esquiline, Caelian, and Palatine Hills.\nBegun under Vespasian, completed under Titus, and used extensively by Domitian, who added underground passages (hypogeum) and improved facilities.\nIt hosted gladiatorial games, beast hunts, and public spectacles.\nNearby stood the Colossus of Nero, a massive statue that gave the amphitheater its nickname: Colosseum.\n\n---\n\n## Other Landmarks\n### Forum Romanum\nCentral plaza lined with temples (Saturn, Vesta, Castor & Pollux), law courts, and triumphal arches.\n\n### Campus Martius\nA flat area north of the city center, filled with bathhouses, theaters, and temples; used for assemblies and training soldiers.- Domitian’s Stadium (modern Piazza Navona) stands here.  \n\n### Circus Maximus\nAn enormous chariot-racing stadium at the base of the Palatine Hill. Could seat up to 250,000 people.\n\n### Baths of Titus\nLarge public bathhouse complex near the Colosseum.  \n\n---\n\n## The Tiber River\nTiber — Waterway, Trade, Island, Bridges  \nRan along the city’s western edge.\nThe Tiber Island hosted a temple to Aesculapius (the god of healing).\nBridges like the Pons Fabricius and Pons Aemilius linked the city center to the Trastevere district on the western bank.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "902888f7-31bc-4ffa-bc49-3fb6244caee4",
    "inclusionGroupRaw": "",
    "insertion_order": 100,
    "key": [
      "Rome",
      "Palatine",
      "Colosseum",
      "Forum",
      "Capitol",
      "Aventine",
      "Esquiline",
      "Circus",
      "Tiber",
      "Temples",
      "Empire",
      "Baths",
      "Stadium",
      "Domus Flavia",
      "Domus Augustana",
      "Marble",
      "Aqueducts",
      "Urban",
      "Architecture",
      "Crowds",
      "Location",
      "Locations",
      "POI",
      "POIs",
      "Places",
      "Monument",
      "Monuments",
      "Establishment",
      "Establishments",
      "District",
      "Districts",
      "Zone",
      "Zones",
      "Area",
      "Areas",
      "River",
      "Rivers"
    ],
    "keyMatchPriority": true,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Rome, Palatine, Colosseum, Forum, Capitol, Aventine, Esquiline, Circus, Tiber, Temples, Empire, Baths, Stadium, Domus Flavia, Domus Augustana, Marble, Aqueducts, Urban, Architecture, Crowds, Location, Locations, POI, POIs, Places, Monument, Monuments, Establishment, Establishments, District, Districts, Zone, Zones, Area, Areas, River, Rivers",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Ancient Rome Overview",
    "prioritizeInclusion": false,
    "priority": 1,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "world",
      "lore"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Vespasian (Titus Flavius Vespasianus)\n- Born: AD 9\n- Died: AD 79\n- Role: Founder of the Flavian dynasty, father of Titus and Domitian\n- Profile: A capable general who rose to power after the chaos of AD 69, Vespasian restored order to Rome and established the Flavian dynasty. Known for his practical nature, wit, and military success, he reigned for ten years before his death in AD 79. His legacy still shapes Domitian’s reign in AD 90.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "dfd79fd5-9bf5-4653-ab91-3b0841ddfbf8",
    "inclusionGroupRaw": "",
    "insertion_order": 200,
    "key": [
      "Vespasian",
      "Vespasianus",
      "Flavian",
      "Patriarch",
      "Emperor"
    ],
    "keyMatchPriority": true,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Vespasian, Vespasianus, Flavian, Patriarch, Emperor",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Vespasian (Titus Flavius Vespasianus)",
    "prioritizeInclusion": false,
    "priority": 2,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "character"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Titus (Titus Flavius Vespasianus)\n- Born: AD 39\n- Died: AD 81\n- Role: Elder brother of Domitian, Emperor of Rome 79–81\n- Profile: Celebrated for his military command in Judea, culminating in the capture of Jerusalem in AD 70. He succeeded Vespasian and ruled briefly, earning popularity for his generosity and public works. His sudden death in AD 81 left Domitian as sole emperor. At the height of his career in AD 90, Norbanus served as Praetorian Prefect under Domitian. A seasoned officer and trusted figure, he commanded the emperor’s elite guard with discipline and loyalty. His reputation was one of steadfast service, ensuring the security of the palace and the emperor himself. Though less visible in political maneuvering, his role was critical to maintaining Domitian’s authority and safety.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "aecd12e9-d70c-4846-9610-084af8b14884",
    "inclusionGroupRaw": "",
    "insertion_order": 300,
    "key": [
      "Titus",
      "Emperor",
      "Flavian",
      "Brother"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Titus, Emperor, Flavian, Brother",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Titus (Titus Flavius Vespasianus)",
    "prioritizeInclusion": false,
    "priority": 3,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "character"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Gnaeus Domitius Corbulo\n- Born: c. AD 7\n- Died: AD 67\n- Role: Celebrated Roman general, father of Empress Domitia Longina\n- Profile: Corbulo was one of Rome’s most respected military commanders of the mid-first century. Serving under the emperors Claudius and Nero, he earned fame for his campaigns in Germania and Armenia, where his strict discipline and tactical brilliance restored Roman strength on the eastern frontier. Admired for his iron will and devotion to Rome, Corbulo became a symbol of military virtue. His end came in AD 67, when Emperor Nero, jealous of his popularity, ordered him to commit suicide. His legacy lived on through his daughter, Domitia Longina, now empress beside Domitian. Among Romans, his name still evoked respect as the model of a true soldier.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "f434e1c7-9a59-4784-ad29-eaf83a75d635",
    "inclusionGroupRaw": "",
    "insertion_order": 400,
    "key": [
      "Corbulo",
      "Gnaeus",
      "Domitius",
      "General",
      "Corbulo",
      "Domitia’s father"
    ],
    "keyMatchPriority": true,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Corbulo, Gnaeus, Domitius, General, Corbulo, Domitia’s father",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Gnaeus Domitius Corbulo",
    "prioritizeInclusion": false,
    "priority": 4,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "character"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Cassia Longina\n- Born: c. AD 30\n- Age in AD 90: about 60\n- Role: Mother of Empress Domitia Longina, widow of Corbulo\n- Profile: Born into the distinguished Cassius family, Cassia Longina married the celebrated general Gnaeus Domitius Corbulo. Together they had Domitia Longina, who later became empress beside Domitian. By AD 90, Cassia would have been an elder matron of about sixty years, a living link between the older senatorial nobility and the reigning Flavian dynasty. Though less politically visible than her husband or daughter, her presence embodied both prestige and continuity.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "f719bb6e-2a23-4092-914b-e4c20faec433",
    "inclusionGroupRaw": "",
    "insertion_order": 500,
    "key": [
      "Cassia",
      "Longina",
      "Mother",
      "Corbulo"
    ],
    "keyMatchPriority": true,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Cassia, Longina, Mother, Corbulo,",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Cassia Longina",
    "prioritizeInclusion": false,
    "priority": 5,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "character"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Domitilla the Elder\n- Born: Early 1st century AD\n- Died: Before AD 69\n- Role: Mother of Titus, Domitian, and Domitilla the Younger\n- Profile: Wife of Vespasian and matron of the Flavian family. Though she died before her husband became emperor, she was later honored with titles posthumously. Remembered chiefly as the mother who bore the dynasty’s rulers.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "5d20a773-42a9-4338-8ad2-cefd2705223b",
    "inclusionGroupRaw": "",
    "insertion_order": 600,
    "key": [
      "Domitilla",
      "Elder",
      "Flavian",
      "mother",
      "Matron",
      "Domitilla"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Domitilla, Elder, Flavian, mother, Matron, Domitilla",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Domitilla the Elder",
    "prioritizeInclusion": false,
    "priority": 6,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "character"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Domitilla the Younger\n- Born: Mid-1st century AD\n- Died: Before AD 81\n- Role: Sister of Domitian and Titus\n- Profile: Daughter of Vespasian and Domitilla the Elder, she married into the Roman elite and bore children who survived into Domitian’s reign. Though less politically prominent than her brothers, she helped extend Flavian influence through her lineage.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "15c9efb1-9efb-4b4d-9db2-7e8f84c93806",
    "inclusionGroupRaw": "",
    "insertion_order": 700,
    "key": [
      "Domitilla",
      "Younger",
      "Flavian",
      "Sister",
      "Daughter"
    ],
    "keyMatchPriority": true,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Domitilla, Younger, Flavian, Sister, Daughter",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Domitilla the Younger",
    "prioritizeInclusion": false,
    "priority": 7,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "character"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Titus Flavius Norbanus\n- Born: c. AD 45\n- Age in AD 90: about 45\n- Role: Praetorian Prefect under Domitian\n- Profile: A seasoned soldier elevated to one of the highest posts in the empire, Norbanus served as Praetorian Prefect alongside Titus Petronius Secundus in AD 90. Entrusted with the command of the emperor’s elite guard, he was known for discipline, efficiency, and loyalty to Domitian. Unlike more politically ambitious prefects of the past, Norbanus kept his focus on military matters, ensuring the emperor’s safety and the security of the palace. His authority extended over thousands of men, making him a quiet but essential pillar of Flavian rule.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "765962dd-7b36-4466-aa6d-14a92057b6f9",
    "inclusionGroupRaw": "",
    "insertion_order": 800,
    "key": [
      "Norbanus",
      "Praetorian",
      "Prefect",
      "Guard",
      "Commander"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Norbanus, Praetorian, Prefect, Guard, Commander",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Titus Flavius Norbanus (Prefect)",
    "prioritizeInclusion": false,
    "priority": 8,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "character"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Julia Flavia\n- Born: c. AD 69\n- Age in AD 90: about 21\n- Role: Niece of Domitian, daughter of Titus\n- Profile: Julia Flavia was the only daughter of Emperor Titus and the sole surviving young member of the Flavian household aside from Domitian himself. By AD 90, she was in her early twenties, admired for her beauty and noble bearing. As the niece of the reigning emperor, she embodied both dynastic prestige and a fragile hope for continuity of the Flavian bloodline. Her presence at court tied Domitian’s reign to his beloved brother Titus, serving as a reminder of the family’s recent past and its uncertain future.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "4b54039a-8873-49bc-9ffd-7692361e3467",
    "inclusionGroupRaw": "",
    "insertion_order": 900,
    "key": [
      "Julia",
      "Flavia",
      "Titus",
      "Daughter",
      "Niece",
      "Domitian"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Julia, Flavia, Titus, Daughter, Niece, Domitian",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Julia Flavia",
    "prioritizeInclusion": false,
    "priority": 9,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "character"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Notable Generals and Military Men\n- Marcus Ulpius Traianus (the elder): A seasoned commander, serving as governor of Syria. Trusted with oversight of one of Rome’s most important eastern provinces, he commanded respect among both soldiers and senators.\n- Tettius Julianus: Celebrated for his victory against the Dacians at Tapae in AD 88. By 90, his reputation as a capable general remained strong, standing as one of the few clear military successes of Domitian’s reign.\n- Lucius Julius Ursus: An experienced officer and administrator, connected closely with Domitian’s court. Known for his reliability, he held both military authority and political trust.\n- Praetorian Prefects: Titus Flavius Norbanus and Titus Petronius Secundus, commanders of the Praetorian Guard in AD 90. Their disciplined leadership ensured the emperor’s personal safety and the stability of the capital.\n- Legion Commanders in Moesia & Dacia – Many legates stationed along the Danube frontier were seasoned men, though their individual names are less clearly preserved in the sources. They were critical in Domitian’s continuing standoff with the Dacians after 88.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "5ce0407e-8e9b-4115-8f60-a3d5a364d3c8",
    "inclusionGroupRaw": "",
    "insertion_order": 1000,
    "key": [
      "general",
      "generals",
      "commander",
      "commanders",
      "officer",
      "officers",
      "Traianus",
      "Ulpius",
      "Julianus",
      "Tettius",
      "Ursus",
      "Lucius",
      "Norbanus",
      "Petronius",
      "Secundus",
      "prefect",
      "prefects",
      "praetorian",
      "praetorians"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "general, generals, commander, commanders, officer, officers, Traianus, Ulpius, Julianus, Tettius, Ursus, Lucius, Norbanus, Petronius, Secundus, prefect, prefects, praetorian, praetorians",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Notable Generals and Military Men in AD 90",
    "prioritizeInclusion": false,
    "priority": 10,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "character"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Enemies of Rome\n- Dacians: A powerful people living north of the Danube. Still emboldened after their earlier clashes with Rome, they remained a constant threat along the Moesian frontier. Their king, Decebalus, had proven a capable leader, forcing Domitian to maintain heavy garrisons in the region.\n- Chatti: A Germanic tribe beyond the Rhine frontier. Known for their raids and skirmishes, they challenged Rome’s control of Germania Superior and kept the legions of the Rhine provinces on alert.\n- Sarmatians (Iazyges and Roxolani): Nomadic horsemen of the steppe lands near the Danube. Their mobility and sudden raids made them a dangerous, unpredictable adversary along Rome’s northern borders.\n- Parthians: Though no open war existed in AD 90, the Parthian Empire was always regarded as a rival power in the East. Relations could shift quickly, and Rome’s commanders in Syria remained watchful of any signs of hostility.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "6582052c-d1cd-4d9e-930b-2f2273ede6d8",
    "inclusionGroupRaw": "",
    "insertion_order": 1100,
    "key": [
      "enemy",
      "enemies",
      "Dacian",
      "Dacians",
      "Decebalus",
      "Chatti",
      "Chattan",
      "Germanic",
      "Germans",
      "Sarmatian",
      "Sarmatians",
      "Iazyges",
      "Roxolani",
      "Parthian",
      "Parthians",
      "tribe",
      "tribes",
      "frontier",
      "frontiers"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "enemy, enemies, Dacian, Dacians, Decebalus, Chatti, Chattan, Germanic, Germans, Sarmatian, Sarmatians, Iazyges, Roxolani, Parthian, Parthians, tribe, tribes, frontier, frontiers",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Enemies of Rome in AD 90",
    "prioritizeInclusion": false,
    "priority": 11,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "faction"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Roman Legions\n- By AD 90, Domitian maintained a strong military presence across the empire, especially along volatile frontiers:\n\n# Danube Frontier (Moesia, Pannonia, Dacia border):\n- Legions stationed here bore the brunt of fighting against the Dacians and Sarmatians.\n- Key legions: Legio I Italica, IV Flavia Felix, V Macedonica, XIII Gemina\n\n# Rhine Frontier (Germania Superior & Inferior):\n- Guarded against the Chatti and other Germanic tribes.\n- Key legions: Legio VIII Augusta, XXII Primigenia, I Minervia, VI Victrix\n\n# Eastern Provinces (Syria & Cappadocia)\n- Watched over the Parthian frontier.\n- Key legions: Legio III Gallica, VI Ferrata, X Fretensis, XII Fulminata, XVI Flavia Firma\n\n# Britannia\n- Continued to secure Roman control in the isles.\n- Key legions: Legio II Augusta, IX Hispana, XX Valeria Victrix\n\n# Africa & Egypt:\n- Provided grain security and stability rather than frontier defense.\n- Key legions: Legio III Augusta (Africa), II Traiana Fortis, XXII Deiotariana (Egypt)",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "1ff403c7-34e2-4b6b-b487-eb285d5255c9",
    "inclusionGroupRaw": "",
    "insertion_order": 1200,
    "key": [
      "legion",
      "legions",
      "frontier",
      "frontiers",
      "Danube",
      "Moesia",
      "Pannonia",
      "Dacia",
      "Rhine",
      "German",
      "Germans",
      "Germania",
      "Syrian",
      "Syrians",
      "Cappadocia",
      "Cappadocian",
      "Cappadocians",
      "Britannia",
      "Briton",
      "Britons",
      "Africa",
      "African",
      "Africans",
      "Egypt",
      "Egyptian",
      "Egyptians",
      "Italica",
      "Felix",
      "Macedonica",
      "Gemina",
      "Augusta",
      "Primigenia",
      "Minervia",
      "Victrix",
      "Gallica",
      "Ferrata",
      "Fretensis",
      "Fulminata",
      "Firma",
      "Hispana",
      "Valeria",
      "Deiotariana",
      "Traiana"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "legion, legions, frontier, frontiers, Danube, Moesia, Pannonia, Dacia, Rhine, German, Germans, Germania, Syrian, Syrians, Cappadocia, Cappadocian, Cappadocians, Britannia, Briton, Britons, Africa, African, Africans, Egypt, Egyptian, Egyptians, Italica, Felix, Macedonica, Gemina, Augusta, Primigenia, Minervia, Victrix, Gallica, Ferrata, Fretensis, Fulminata, Firma, Hispana, Valeria, Deiotariana, Traiana",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Roman Legions in AD 90",
    "prioritizeInclusion": false,
    "priority": 12,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "faction"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Rome’s Allies\nRome’s power was supported not only by its legions but also by a network of client kingdoms and allied states. In the East, Armenia served as a critical buffer between Rome and Parthia, its throne filled by client kings acceptable to both powers. The Nabataean Kingdom at Petra ensured safe trade routes through Arabia and supplied auxiliaries when needed, while the dynasty of Emesa in Syria maintained close ties with Roman authority. In the Balkans and the Black Sea, Thrace remained under client kingship, and the Bosporan Kingdom provided naval support, securing the northern seas. In North Africa, Mauretania supplied skilled cavalry, an essential supplement to Rome’s forces. Even remnants of the Herodian dynasty in Judaea, though politically weakened after the Jewish Revolt, still offered loyalty and connection to Rome. These allies formed a web of protection and partnership that extended Roman influence beyond the empire’s formal frontiers.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "cb2c8f2f-353f-45ef-8a00-c00dcc7553b1",
    "inclusionGroupRaw": "",
    "insertion_order": 1300,
    "key": [
      "ally",
      "allies",
      "Armenia",
      "Armenian",
      "Armenians",
      "Nabataea",
      "Nabataean",
      "Nabataeans",
      "Emesa",
      "Emesene",
      "Emesenes",
      "Thrace",
      "Thracian",
      "Thracians",
      "Bosporus",
      "Bosporan",
      "Bosporans",
      "Mauretania",
      "Mauretanian",
      "Mauretanians",
      "Herodian",
      "Herodians",
      "client",
      "clients",
      "kingdom",
      "kingdoms"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "ally, allies, Armenia, Armenian, Armenians, Nabataea, Nabataean, Nabataeans, Emesa, Emesene, Emesenes, Thrace, Thracian, Thracians, Bosporus, Bosporan, Bosporans, Mauretania, Mauretanian, Mauretanians, Herodian, Herodians, client, clients, kingdom, kingdoms",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Rome’s Allies in AD 90",
    "prioritizeInclusion": false,
    "priority": 13,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "faction"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Roman Auxiliaries\nThe strength of Rome’s armies did not rest on the legions alone. By AD 90, auxiliaries formed a vital part of the empire’s military machine, recruited from allied and subject peoples across the provinces. Germanic tribes provided fierce infantry and scouts, while the Batavians were prized for their discipline and cavalry skills. From the East came Syrian and Nabataean archers, valued for their accuracy and mobility. North Africa supplied light cavalry, particularly the swift Numidian and Mauretanian horsemen, who were essential for flanking and pursuit. The Sarmatians contributed heavily armed cavalry, whose shock tactics added weight to Rome’s frontier forces. Auxiliaries were organized into cohorts and alae, stationed along the frontiers to both defend and police the provinces. Many auxiliaries earned Roman citizenship after years of service, tying frontier peoples more closely to the empire.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "f9fcbb94-acc0-4363-9bbb-c4525b483ef2",
    "inclusionGroupRaw": "",
    "insertion_order": 1400,
    "key": [
      "auxiliary",
      "auxiliaries",
      "Batavian",
      "Batavians",
      "German",
      "Germans",
      "Syrian",
      "Syrians",
      "Nabataean",
      "Nabataeans",
      "Numidian",
      "Numidians",
      "Mauretanian",
      "Mauretanians",
      "Sarmatian",
      "Sarmatians",
      "cohort",
      "cohorts",
      "ala",
      "alae"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "auxiliary, auxiliaries, Batavian, Batavians, German, Germans, Syrian, Syrians, Nabataean, Nabataeans, Numidian, Numidians, Mauretanian, Mauretanians, Sarmatian, Sarmatians, cohort, cohorts, ala, alae",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Roman Auxiliaries in AD 90",
    "prioritizeInclusion": false,
    "priority": 14,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "faction"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Imperial Travel:\n- Roman emperors traveled with a blend of ceremony, dignity, and practicality. Within Rome, they often used litters (lecticae) carried by attendants or chariots for formal appearances. Across Italy and the provinces, emperors employed carriages (raeda or carpentum), supported by the cursus publicus, the state-run postal and transport system providing fresh horses and vehicles at official waystations. On campaign or frontier inspections, emperors rode horseback. River and sea travel was conducted via imperial ships and boats, particularly along the Tiber and through Ostia, ensuring swift movement to villas and provincial posts.\n\n# Senatorial and Noble Travel:\n- Senators and nobles traveled with dignity and display, though on a smaller scale. Within Rome, they often used litters (lecticae) for comfort or processions. Longer journeys employed carriages (raeda or carpentum) drawn by horses or mules, usually accompanied by a retinue of attendants or clients. Horseback riding was common for estate inspections or military oversight. River and coastal travel relied on private boats, particularly along the Tiber or through Ostia, balancing prestige, safety, and practicality.\n\n# Citizen Travel:\n- Ordinary citizens traveled primarily on foot or with simple vehicles. Within cities, most walked, occasionally using public wagons or carts to transport goods. Wealthier citizens might have a private carriage or small cart, while horseback was rare and generally limited to rural landowners or messengers. For long-distance travel, citizens relied on coaches, carts, or pack animals, using the cursus publicus only for official business. River and coastal travel occurred via merchant boats or ferries. Citizens’ travel emphasized practicality and necessity over display.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "fba4df34-8f11-4791-a2e9-64d5c90229ec",
    "inclusionGroupRaw": "",
    "insertion_order": 1500,
    "key": [
      "litter",
      "litters",
      "lectica",
      "chariot",
      "chariots",
      "carriage",
      "carriages",
      "raeda",
      "carpentum",
      "horse",
      "horses",
      "horseback",
      "ship",
      "ships",
      "vessel",
      "vessels",
      "boat",
      "boats",
      "Tiber",
      "Ostia",
      "emperor",
      "emperors",
      "senator",
      "senators",
      "noble",
      "nobles",
      "elite",
      "retinue",
      "attendant",
      "attendants",
      "foot",
      "walking",
      "walker",
      "wagon",
      "wagons",
      "cart",
      "carts",
      "pack",
      "packs",
      "packanimal",
      "packanimals",
      "messenger",
      "messengers",
      "citizen",
      "citizens",
      "commoner",
      "commoners",
      "plebeian",
      "plebeians",
      "traveler",
      "travelers"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "litter, litters, lectica, chariot, chariots, carriage, carriages, raeda, carpentum, horse, horses, horseback, ship, ships, vessel, vessels, boat, boats, Tiber, Ostia, emperor, emperors, senator, senators, noble, nobles, elite, retinue, attendant, attendants, foot, walking, walker, wagon, wagons, cart, carts, pack, packs, packanimal, packanimals, messenger, messengers, citizen, citizens, commoner, commoners, plebeian, plebeians, traveler, travelers",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Transportation (AD 90)",
    "prioritizeInclusion": false,
    "priority": 15,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "technology"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Roman Weaponry (AD 90)\n- Roman soldiers and citizens relied on a variety of weapons depending on rank, role, and purpose.\n\nLegionary Arms:\n- Gladius: The standard short sword of the legionary, designed for close combat and thrusting.\n- Pilum: A heavy javelin used to disrupt enemy formations before engaging with the gladius.\n- Scutum: Large rectangular shield, providing protection in formation.\n- Pugio: A small dagger carried as a secondary weapon.\n- Helmets (Galea), armor (lorica segmentata, lorica hamata), and greaves completed the legionary’s kit.\n\nAuxiliary Arms:\n- Longer swords (spatha) for cavalry and some infantry auxiliaries.\n- Bows and slings provided ranged support, particularly from Germanic, Eastern, and North African units.\n- Spears and javelins supplemented legionary pila, used for both throwing and thrusting.\n\nCavalry Arms:\n- Swords (spatha), lances (hastae), and bows were common among Roman cavalry and allied horsemen.\n- Shields (parma, clipeus) provided mobility without encumbering mounted troops.\n\nCivilian and Elite Arms:\n- Nobles, senators, and citizens might carry daggers (pugiones) or ceremonial swords during parades. Wealthier elites could also sponsor gladiatorial equipment or private guards.\n\nSiege and Support Weapons:\n- Ballistae, onagers, and scorpions were used in frontier forts and during campaigns to hurl stones, bolts, and projectiles.\n- Fortification tools like pilae, stakes, and portable towers supported legionary operations.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "e55ac3cf-16f7-4bde-9a84-6e01ed33a299",
    "inclusionGroupRaw": "",
    "insertion_order": 1600,
    "key": [
      "gladius",
      "gladii",
      "pilum",
      "pila",
      "scutum",
      "scuta",
      "pugio",
      "pugiones",
      "spatha",
      "spathae",
      "hasta",
      "hastae",
      "bow",
      "bows",
      "sling",
      "slings",
      "sword",
      "swords",
      "dagger",
      "daggers",
      "shield",
      "shields",
      "parma",
      "clipeus",
      "helmet",
      "helmets",
      "galea",
      "lorica",
      "loricae",
      "segmentata",
      "hamata",
      "greave",
      "greaves",
      "ballista",
      "ballistae",
      "onager",
      "onagers",
      "scorpion",
      "scorpions",
      "siege",
      "fortification",
      "spear",
      "spears",
      "javelin",
      "javelins",
      "cavalry",
      "legionary",
      "auxiliary",
      "auxiliary",
      "weapon",
      "weapons",
      "weaponry",
      "arsenal"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "gladius, gladii, pilum, pila, scutum, scuta, pugio, pugiones, spatha, spathae, hasta, hastae, bow, bows, sling, slings, sword, swords, dagger, daggers, shield, shields, parma, clipeus, helmet, helmets, galea, lorica, loricae, segmentata, hamata, greave, greaves, ballista, ballistae, onager, onagers, scorpion, scorpions, siege, fortification, spear, spears, javelin, javelins, cavalry, legionary, auxiliary, auxiliary, weapon, weapons, weaponry, arsenal",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Roman Weaponry (AD 90)",
    "prioritizeInclusion": false,
    "priority": 16,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "technology"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Julio-Claudian Dynasty (27 BCE – 68 CE)\n- Augustus — 27 BCE to 14 CE\n- Tiberius — 14 to 37 CE\n- Caligula (Gaius) — 37 to 41 CE\n- Claudius — 41 to 54 CE\n- Nero — 54 to 68 CE\n(The Julio-Claudian line ends with Nero’s death, leading to a civil war known as the “Year of the Four Emperors.”)\n\n# Year of the Four Emperors (68–69 CE)\n- Galba — 68 to 69 CE\n- Otho — 69 CE\n- Vitellius — 69 CE\n\n# Flavian Dynasty (69–96 CE)\n- Vespasian — 69 to 79 CE\n- Titus — 79 to 81 CE\n- Domitian — 81 to present",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "28ccc82d-72ce-45ca-a583-d9c212b5a932",
    "inclusionGroupRaw": "",
    "insertion_order": 1700,
    "key": [
      "Augustus",
      "Tiberius",
      "Caligula",
      "Claudius",
      "Nero",
      "Galba",
      "Otho",
      "Vitellius",
      "Vespasian",
      "Titus",
      "Reign",
      "Rulers",
      "Ruler"
    ],
    "keyMatchPriority": true,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Augustus, Tiberius, Caligula, Claudius, Nero, Galba, Otho, Vitellius, Vespasian, Titus, Reign, Rulers, Ruler,",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Roman Emperors Masterlist",
    "prioritizeInclusion": false,
    "priority": 17,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "lore",
      "history"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# King Duras (also known as Diurpaneus) \n- Reigned roughly c. 69–87 CE\n- Predecessor of Decebalus.\n- Engaged in early conflicts with Rome under Emperor Domitian.\n\n# King Decebalus – Reign started during c. 87 CE\n- Rules as a warrior-king and reformer, uniting the Dacian tribes under a central monarchy.\n- Intelligent, strategic, and charismatic\n- Defeated a Roman army under Cornelius Fuscus in 87 CE, forcing Emperor Domitian to negotiate peace.\n- He defeated several Roman commanders early in Domitian’s campaigns (notably Oppius Sabinus), forcing Rome to sign a peace treaty around 89 CE, which made Decebalus a client king—in name a Roman ally, but effectively independent, with the relationship between both remaining tense.\n- His sister was captured by the Romans during the first war with Trajan and was married into Roman nobility\n\n# Dacian Kingdom 90 CE\n- The kingdom’s heartland lies within the Transylvanian Basin, surrounded by forested ridges and steep valleys that form a natural fortress.\n- To the south runs the Danube River, the boundary with the Roman province of Moesia.\n- Fortresses crown high plateaus and mountain passes, connected by stone roads and defended with walls, terraces, and sanctuaries.\n- The Dacians have carved their capital, Sarmizegetusa Regia, into the Orăștie Mountains — a complex of citadels, temples, and noble residences.\n- The nobles serve as local chieftains, priests, and commanders, while the commoners provide labor and form the backbone of the army.\n- Society is divided between nobles (tarabostes or pileati) and commoners (comati).\n\n# Tribes\n- The kingdom was composed of multiple Dacian tribes (such as the Carpi, Costoboci, and Buridavenses), united under the king’s leadership. These tribes retained some local autonomy but owed allegiance and military support to the crown.\n\n# Economy & Resources\n- Dacia’s mineral wealth—especially the gold mines of the Apuseni Mountains—makes it one of the most coveted lands north of the Danube.\n- Metalworking, woodworking, and pottery are advanced; Dacian craftsmen produce weapons, jewelry, and fine ceramics traded across the Danube.\n- Agriculture thrives in valleys: wheat, barley, livestock, and vineyards sustain both villages and armies.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "fc337b73-59e4-4e19-b9f0-ce8b51ecad5a",
    "inclusionGroupRaw": "",
    "insertion_order": 1800,
    "key": [
      "Dacia",
      "Dacian",
      "Duras",
      "Decebal",
      "Decebalus",
      "Diurpaneus",
      "Danube",
      "Sarmizegetusa",
      "Orăștie"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Dacia, Dacian, Duras, Decebal, Decebalus, Diurpaneus, Danube, Sarmizegetusa, Orăștie",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Dacian Kingdom",
    "prioritizeInclusion": false,
    "priority": 18,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "faction",
      "Enemy"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# King of Kings\n- Both Pacorus II and Vologases I were kings of Parthia, but they lived and ruled during different generations of the Arsacid (Parthian) dynasty. By 90 CE, Pacorus II was the reigning Parthian king, while Vologases I had died decades earlier.\n\n# Vologases I (reigned c. 51–78 CE)\n- Vologases I was a powerful early king of Parthia, ruling during the mid-1st century CE.\n- He sought to strengthen Parthian unity and control over Armenia, a crucial buffer state between Rome and Parthia.\n- His attempt to place his brother Tiridates I on the Armenian throne sparked conflict with Emperor Nero around 58–63 CE.\n- The resulting Roman–Parthian War ended with a compromise: Tiridates was recognized as king but had to receive his crown formally from Nero in Rome.\n- Vologases I’s reign helped stabilize Parthia after internal dynastic strife and laid the groundwork for later rulers like Pacorus II.\n- Both Parthian and Roman empires were exhausted from earlier Roman–Parthian wars under Nero and Vologases I (58–63 CE), resulting in fragile peace, with the relationship between the two empires being tense but somewhat stable.\n- He died around 78 CE, succeeded by Pacorus II\n\n## Vologases I's family and relatives\n- An Arsacid wife\n- brother, Tiridates I of Armenia — (deceased, 88 CE) installed as King of Armenia by Vologases, sparking the Roman–Parthian War during Nero’s reign.\n- brother, Pacorus (not the same as Pacorus II) — ruled Media or another eastern province.\n- Sons \n  - Pacorus II (r. 78–present)\n  - Vardanes II (Deceased. r. 54–58)\n  - Vologases II (Deceased r. 78–80)\n  - Artabanus III (Deceased r. 79/80–81)\t\n\n# Pacorus II (reigned c. 78–present)\n- By 90 CE, Pacorus II was the King of Kings of Parthia.\n- His reign was marked by both internal civil wars and cautious diplomacy with Rome.\n- Early in his rule, he faced rival claimants to the throne (notably Vologases II and Artabanus III).\n- Despite the internal strife, Pacorus II maintained overall control of Parthia and secured its eastern borders.\n- He avoided major conflict with Emperor Domitian, instead focusing on consolidating power and managing Armenia through indirect influence.\n- Pacorus II’s reign saw cultural flourishing — Parthian coins from this era show a mixture of Greek and Persian iconography, signaling a confident, blended identity. \n\n# Pacorus II's family and relatives\n- Brothers and Rivals Vologases II and Artabanus III who both claimed the throne during parts of Pacorus II’s reign, leading to civil wars.\n- An Arsacid wife\n\n# Military\n- Parthia’s power rests on its cavalry—both cataphracts (heavily armored horsemen) and mounted archers skilled in the famed “Parthian shot.”\n- The army is largely composed of noble levies, each aristocrat raising his own contingent.\n- Standing forces are limited, relying on swift mobilization through feudal obligation.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "8e8a9c40-db97-4c5d-8e70-4bd063d7f73c",
    "inclusionGroupRaw": "",
    "insertion_order": 1900,
    "key": [
      "Vologases",
      "Arsacid",
      "Ctesiphon",
      "Parthia",
      "Persia",
      "Armenia"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Vologases, Arsacid, Ctesiphon, Parthia, Persia, Armenia, ",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Parthian Empire",
    "prioritizeInclusion": false,
    "priority": 19,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "faction",
      "Enemy"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Pacorus of Media Atropatene\n- Elder brother of the late Vologases I\n- Pacorus was a son of Vonones II (r. 51). \n- When Vonones II died in 51, his son Vologases I became the new Parthian king.\n- a Parthian prince who ruled Media Atropatene\n\n# Alans\n- in 72, a group of Alans invaded his kingdom and forced him to flee into the mountains. \n- Pacorus was forced to pay the Alans to have his wife and concubines released from captivity.[5] The Alans also invaded Armenia, and nearly captured Tiridates in battle; he was lassoed from a distance and caught, but he quickly managed to whip out his sword and slash the rope in time.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "571bf10a-b082-4dc0-83b6-d56e8714ef0a",
    "inclusionGroupRaw": "",
    "insertion_order": 2000,
    "key": [
      "Pacorus",
      "Pacorus I",
      "Pakorus"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Pacorus, Pacorus I, Pakorus",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Pacorus I",
    "prioritizeInclusion": false,
    "priority": 20,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "character"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Pacorus II\n- Son of Vologases I\n- Pacorus was soon met by a revolt by his brother Vologases II, which lasted until the latter's defeat in 80\n- Pacorus' brothers Vologases II and Artabanus III who both claimed the throne during parts of Pacorus II’s reign, leading to civil wars. (competed with Pacorus II for the Parthian crown from 78, until both Pacorus' brothers' defeat in 80) ",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "62612101-d723-4bb8-b427-266fb67f95c5",
    "inclusionGroupRaw": "",
    "insertion_order": 2100,
    "key": [
      "Pacorus",
      "Pacorus II",
      "Pakoros"
    ],
    "keyMatchPriority": true,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Pacorus, Pacorus II, Pakoros,",
    "matchWholeWords": false,
    "minMessages": 0,
    "name": "Pacorus II",
    "prioritizeInclusion": false,
    "priority": 21,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "character"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Directly Ruled Roman Provinces (Imperial & Senatorial)\nThese were governed by Roman officials (not kings), but they form the core of Roman dominion.\n\n- Italia – Imperial Crown (no governor).\n- Gallia (Gaul) – Divided into several provinces (Lugdunensis, Aquitania, Belgica), each ruled by Roman governors.\n- Britannia – Governed by Sallustius Lucullus.\n- Hispania – Under Roman provincial governors.\n- Germania Inferior and Superior – Under legates; Roman military provinces.\n- Africa Proconsularis (North Africa) – Ruled by a proconsul.\n- Aegyptus (Egypt) – Governed by an equestrian prefect; Tiberius Julius Lupus (around 90 AD).\n- Syria, Judaea, Cappadocia, Cilicia – Governed by imperial legates, heavily militarized provinces near Parthia and Armenia.\n- Moesia – Roman province south of the Danube (modern Bulgaria/Serbia); capital Viminacium/Novae; governed by an imperial legate; heavily fortified after recent Dacian invasions (85–89 CE); garrisoned by Legio I Italica and V Macedonica; key frontier defense zone.\n- Pannonia – Roman province along the central Danube (modern Hungary/Austria); capital Carnuntum; governed by an imperial legate (L. Funisulanus Vettonianus earlier in Domitian’s reign); major military corridor linking Italy to the northern front; home to Legio XIII Gemina and XV Apollinaris; on alert against Marcomanni, Quadi, and Sarmatians.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "c10c001d-00c0-4c77-9250-d71c5bb4b8d9",
    "inclusionGroupRaw": "",
    "insertion_order": 2200,
    "key": [
      "Provinces",
      "Governors",
      "Empire",
      "Kingdom",
      "Italia",
      "Gallia",
      "Gaul",
      "Britannia",
      "Britain",
      "Hispania",
      "Germania",
      "Africa",
      "Proconsularis",
      "Aegypt",
      "Egypt",
      "Syria",
      "Judaea",
      "Cappadocia",
      "cilicia",
      "moesia",
      "pannonia",
      "Sallustius",
      "Lucullus",
      "Italica",
      "Macedonic"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Provinces, Governors, Empire, Kingdom, Italia, Gallia, Gaul, Britannia, Britain, Hispania, Germania, Africa, Proconsularis, Aegypt, Egypt, Syria, Judaea, Cappadocia, cilicia, moesia, pannonia, Sallustius, Lucullus, Italica, Macedonic, ",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Direct Rulership",
    "prioritizeInclusion": false,
    "priority": 22,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "faction"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Client Kingdoms under Roman Authority (Semi-Autonomous States)\nThese rulers were loyal to Rome, often installed or approved by the Emperor.\n\n## Eastern Mediterranean\n- Armenia – Sanatruces II — an Arsacid prince approved by both Parthia and Rome to maintain peace.\n- Commagene (Syria region) – Officially annexed by Rome in 72 AD, now under a Roman governor by 90 AD.\n- Cappadocia – Fully Roman province since Claudius; no local king.\n- Nabataean Kingdom (Arabia Petraea) – King Rabbel II Soter (r. since 70 AD) — loyal client of Rome, maintaining trade routes in Arabia and Judea.\n- Emesa (Syria) – Sampsigeramus IV Mattabel (r. c. since 78 AD) — local Arab client king under Rome’s protection.\n- Iturea – Integrated into Roman Syria, no longer ruled by local kings.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "083bd884-a120-4896-9959-433d39e3868f",
    "inclusionGroupRaw": "",
    "insertion_order": 2300,
    "key": [
      "Client",
      "Eastern",
      "Mediterranean",
      "Armenia",
      "Syria",
      "Commagene",
      "Cappadocia",
      "Arabia",
      "Nabataea",
      "Nabataean",
      "Emesa",
      "Syria",
      "Iturea",
      "Sanatruces",
      "Rabbel",
      "Sotter",
      "Sampsigeramus",
      "Mattabel"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Client, Eastern, Mediterranean, Armenia, Syria, Commagene, Cappadocia, Arabia, Nabataea, Nabataean, Emesa, Syria, Iturea, Sanatruces, Rabbel, Sotter, Sampsigeramus, Mattabel, ",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Eastern Mediterranean Client Kingdoms",
    "prioritizeInclusion": false,
    "priority": 23,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "faction"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Client Kingdoms under Roman Authority (Semi-Autonomous States)\nThese rulers were loyal to Rome, often installed or approved by the Emperor.\n\n## Balkan & Black Sea Region\n- Bosporan Kingdom (Crimea) – King Sauromates I (r. c. 93 AD) or possibly still King Rhescuporis II in early 90s — client kings loyal to Rome, maintaining control over trade and grain routes.\n- Thrace – King Rhoemetalces II (r. c. 79–90 AD), Rhoemetalces III after him — Thracian client kings allied with Rome.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "c7cbf407-505d-4ae4-8a7b-964cfab601ab",
    "inclusionGroupRaw": "",
    "insertion_order": 2400,
    "key": [
      "Client",
      "Balkan",
      "Black",
      "Sea",
      "Thrace",
      "Bosporus",
      "Cimmerian",
      "Cimmeria",
      "Crimea",
      "Sauromates",
      "Rhoemetalces"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Client, Balkan, Black, Sea, Thrace, Bosporus, Cimmerian, Cimmeria, Crimea, Sauromates, Rhoemetalces",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Balkan and Black Sea Region Client Kingdoms",
    "prioritizeInclusion": false,
    "priority": 24,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "faction"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Client Kingdoms under Roman Authority (Semi-Autonomous States)\nThese rulers were loyal to Rome, often installed or approved by the Emperor.\n\n## Near East\n- Judea/Syria Region – Direct Roman rule, but small local dynasties like Agrippa II (r. since 48 AD) of the Herodian line still ruled Chalcis and parts of northern Palestine under Roman oversight.\n- Osroene (Edessa) – King Abgar VII (r. since 85 AD) — a loyal Parthian-born client king friendly to Rome.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "55f94591-bd20-4896-9cab-5e3922a2e155",
    "inclusionGroupRaw": "",
    "insertion_order": 2500,
    "key": [
      "Client",
      "Judea",
      "Syria",
      "Osroene",
      "Edessa",
      "Abgar",
      "Agrippa",
      "Eastern"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Client, Judea, Syria, Osroene, Edessa, Abgar, Agrippa, Eastern",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Near East Client Kingdoms",
    "prioritizeInclusion": false,
    "priority": 25,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "faction"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "# Client Kingdoms under Roman Authority (Semi-Autonomous States)\nThese rulers were loyal to Rome, often installed or approved by the Emperor.\n\n## Arabia and North Africa\n- Mauretania (modern Algeria/Morocco) – Divided into Mauretania Caesariensis and Mauretania Tingitana, both ruled by Roman governors since the fall of the last client kings (Ptolemy of Mauretania died 40 AD).\n- Cyrenaica, Egypt – Directly under Roman prefects.",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "89d15bb7-8e6e-41c6-a385-0582b65ef984",
    "inclusionGroupRaw": "",
    "insertion_order": 2600,
    "key": [
      "Arabia",
      "North",
      "Africa",
      "Arabian",
      "African",
      "Mauretania",
      "Caesariensis",
      "Tingitana",
      "Cyrenaica",
      "Egypt"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Arabia, North, Africa, Arabian, African, Mauretania, Caesariensis, Tingitana, Cyrenaica, Egypt",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Arabian and African Client Kingdoms",
    "prioritizeInclusion": false,
    "priority": 26,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "faction"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "## The Flavian Amphitheater\n- commonly known as the Colosseum, stands as the grandest arena in the empire, hosting bloodsport for tens of thousands of spectators.\n- Gladiators range from condemned criminals and prisoners of war to volunteers seeking fortune and fame.\n- Nobles, merchants, and senators wager vast sums on combat outcomes, influencing matches behind the scenes.\n- Training regimens are brutal, designed to harden men into killers for the entertainment of the masses.\n\n## Control and Oversight\n- The lanista, a former gladiator or military veteran, oversees training and discipline.\n- Doctores (trainers) instruct recruits in combat techniques.\n- The Dominus (owner) holds ultimate authority, often a wealthy noble or senator.\n\n## Training Grounds\n- Open-air courtyard with sand-covered floors for sparring.\n- Wooden dummies, blunted weapons, and weighted training gear.\n- Spectators sometimes watch to scout talent.\n\n## Holding Cells\n- Dark chambers beneath the arena.\n- The clang of gates signals combat.\n- Wild beasts kept separately for spectacle fights.\n\n## Feasting Hall / Slave Quarters\n- Communal dining hall where fighters eat simple but high-protein meals.\n- Slaves and attendants tend to wounded gladiators, clean, and distribute rations.\n\n## Medical and Treatment Areas\n- A rudimentary infirmary with Roman medici (physicians).\n- Limited treatments, often crude amputations or cauterizations.\n- Healers prioritize valuable fighters over disposable ones.\n\n## Administrative and Noble Viewing Areas\n- Exclusive seating for the emperor, senators, and high-ranking officials. A safe and long distance away from the arena",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "780978de-e14e-46fd-aa95-0ef7bfc4acac",
    "inclusionGroupRaw": "",
    "insertion_order": 2700,
    "key": [
      "Colosseum",
      "Arena",
      "Amphitheater",
      "Gladiator",
      "Gladiators",
      "Lanista",
      "Lanistas"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Colosseum, Arena, Amphitheater, Gladiator, Gladiators, Lanista, Lanistas, ",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "The Flavian Amphitheater",
    "prioritizeInclusion": false,
    "priority": 27,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "location"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "The Traditional Roman State Religion is the official civic religion of Rome, binding the city and empire to the favor of its gods through ritual, sacrifice, and public observance. It is not simply a matter of personal belief; participation is considered a duty of citizenship. The well-being of the state, the success of armies, and the prosperity of the populace are all thought to depend on the proper performance of these sacred rites.\n\nThe Traditional Roman State Religion is both a religious and civic institution, practiced by priests, magistrates, and citizens alike. Its temples dominate cityscapes, its rituals punctuate the calendar, and its festivals unite the population in shared worship. Success in war, prosperity, and the favor of the gods are intertwined, making devotion to the state gods a matter of public duty and personal honor.\n\n## Worshippers\n- All Roman citizens, particularly male citizens, are expected to participate in civic ceremonies.\n- Priestly colleges perform specialized rites: Pontifices oversee all state religious laws and major ceremonies. Augures interpret omens from birds, thunder, and celestial phenomena. Vestal Virgins maintain the sacred fire of Vesta and perform domestic and public rites.\n- Magistrates, senators, and military commanders sponsor public sacrifices and festivals to demonstrate piety and gain favor.\n- Common citizens contribute through offerings, participation in festivals, and observance of household rituals at family shrines (lararia).",
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "cb2a73db-d5d1-4e45-9644-bccbc82da08e",
    "inclusionGroupRaw": "",
    "insertion_order": 2800,
    "key": [
      "Jupiter",
      "Mars",
      "Juno",
      "Minerva",
      "Pontifices",
      "Vestal Virgins",
      "Temples",
      "Lararia",
      "Sacrifice",
      "Festivals",
      "Civic Religion",
      "Capitoline",
      "Forum",
      "Household Worship."
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Jupiter, Mars, Juno, Minerva, Pontifices, Vestal Virgins, Temples, Lararia, Sacrifice, Festivals, Civic Religion, Capitoline, Forum, Household Worship.",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Traditional Roman State Religion",
    "prioritizeInclusion": false,
    "priority": 28,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "culture"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "## Roman Clothing Colors - Spartan Version\n\nWhite  \n- Gods: Jupiter, Vesta  \n- Worn by: Citizens, priests, magistrates, candidates  \n- Meaning: Purity, civic duty, ritual\n\nPurple  \n- Gods: Jupiter, Minerva  \n- Worn by: Emperor, senators, elites, high priests  \n- Meaning: Power, authority, wealth\n\nRed  \n- Gods: Mars, Bellona  \n- Worn by: Soldiers, generals, magistrates, cults  \n- Meaning: Courage, war, blood, vitality\n\nBlue  \n- Gods: Dis Pater, Proserpina  \n- Worn by: Soldiers, lower-class citizens  \n- Meaning: Sky, loyalty, calm\n\nBlack  \n- Gods: Dis Pater, Proserpina, Hades  \n- Worn by: Mourning, priests, slaves, lower-class citizens  \n- Meaning: Death, mourning, humility\n\nGreen  \n- Gods: Ceres, Flora  \n- Worn by: Citizens, merchants, entertainers, some military  \n- Meaning: Fertility, nature, renewal\n\nYellow / Gold  \n- Gods: Sol, Apollo  \n- Worn by: Nobility, priests, wealthy merchants  \n- Meaning: Wealth, prosperity, divine favor\n\nBrown / Earth  \n- Gods: Neptune, Jupiter  \n- Worn by: Commoners, slaves, laborers  \n- Meaning: Humility, labor, practicality",
    "depth": 1,
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "cba3fb76-4bb0-458d-addb-8ea56e13a1a0",
    "inclusionGroupRaw": "",
    "insertion_order": 2900,
    "key": [
      "Cloth",
      "Clothes",
      "Clothing",
      "Wear",
      "Wearing",
      "Attire",
      "Color",
      "White",
      "Purple",
      "Red",
      "Blue",
      "Black",
      "Green",
      "Yellow",
      "Gold",
      "Brown",
      "Earth"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "Cloth, Clothes, Clothing, Wear, Wearing, Attire, Color, White, Purple, Red, Blue, Black, Green, Yellow, Gold, Brown, Earth",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "Roman Colors and Clothing",
    "prioritizeInclusion": false,
    "priority": 29,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "culture"
    ]
  },
  {
    "activationMode": "standard",
    "activationScript": "",
    "case_sensitive": false,
    "category": "other",
    "comment": "",
    "constant": false,
    "content": "• 27 BC\nOctavian becomes Augustus, marking the start of the Roman Empire and the end of the Republic.\n\n• 19 BC\nCompletion of major Augustan reforms and consolidation of imperial power.\n\n• 9 AD\nThe Varian Disaster in the Teutoburg Forest, where three Roman legions are destroyed by Germanic tribes. This halts Rome’s expansion into Germania.\n\n• 14 AD\nDeath of Augustus. Tiberius becomes emperor.\n\n• 37 AD\nDeath of Tiberius. Caligula rises to power.\n\n• 41 AD\nAssassination of Caligula. Claudius becomes emperor.\n\n• 43 AD\nClaudius orders the conquest of Britain, adding it to the empire.\n\n• 54 AD\nNero becomes emperor.\n\n• 64 AD\nThe Great Fire of Rome. Much of the city burns and Nero begins major rebuilding.\n\n• 68–69 AD\nThe Year of the Four Emperors. Nero dies, followed by a chaotic struggle between Galba, Otho, Vitellius, then Vespasian who stabilizes the empire.\n\n• 70 AD\nVespasian and Titus crush the First Jewish Revolt. Jerusalem is destroyed and the Second Temple is burned.\n\n• 79 AD\nMount Vesuvius erupts. Pompeii, Herculaneum, and nearby towns are buried.\n\n• 79 AD\nTitus becomes emperor after Vespasian's death.\n\n• 80 AD\nThe Colosseum is completed and inaugurated with games.",
    "depth": 1,
    "enabled": true,
    "extensions": {},
    "groupWeight": 100,
    "id": "37cd0a86-ebd5-4a9e-a78e-df59dd412346",
    "inclusionGroupRaw": "",
    "insertion_order": 3000,
    "key": [
      "History",
      "Varian",
      "Disaster",
      "Teutoburg",
      "Great Fire",
      "Vesuvius",
      "Pompeii",
      "Herculaneum",
      "Caligula",
      "Britain"
    ],
    "keyMatchPriority": false,
    "keysecondary": [],
    "keysecondaryRaw": "",
    "keysRaw": "History, Varian, Disaster, Teutoburg, Great Fire, Vesuvius, Pompeii, Herculaneum, Caligula, Britain",
    "matchWholeWords": true,
    "minMessages": 0,
    "name": "History prior 90 AD",
    "prioritizeInclusion": false,
    "priority": 30,
    "probability": 100,
    "selectiveLogic": 0,
    "tags": [
      "event",
      "lore"
    ]
  }
]
